### PR TITLE
convert .rvmrc to .ruby-version and .ruby-gemset

### PR DESCRIPTION
**Pull request by harryw**
These files are the agreed standard for RVM, rbenv and perhaps other Ruby version management tools.

They're also pure data, not executable code, which makes them safer.

### CODE REVIEW

**Comment by mjobin-mdsol** [comment]
I agree with this but wonder, if we really need to keep the gemset ? maybe .ruby-version is enough

**Comment by harryw** [comment]
Yeah I'd tend to agree - I don't find gemsets useful. This is just a direct conversion from the .rvmrc file.

Happy to make that change if @asmith-mdsol wants it.

While we're at it, perhaps we could update the Ruby version too.

**Comment by mjobin-mdsol** [comment]
especially that tests on Travis runs for 1.9.3 and 2.0.0 successfully,... maybe dice_bag don't actually need a .ruby-version at all

whatever the user has as default should be work... and this is only for developers running tests.
when included as a gem, these files does nothing.

I vote to remove them both

**Comment by jcarres-mdsol** [comment]
yes update to at least 1.9.3
I personally do not use gemsets ever but I think some people are still using them. 
It guess it doesn't  hurt to keep it?

**Comment by clabrunda** [comment]
I wasn't aware that anyone didn't use gemsets.  I love gemsets, so I vote keep the files.  This PR looks good to me.

**Comment by asmith-mdsol** [comment]
I'm no fan of gemsets any more, having been converted to rbenv and local bundling a while back. However, we have at least one "pro" voice and I don't see particular harm keeping it around. I'll merge this for now as it's an improvement on the status quo.

I'd like to give a little more thought on whether we should remove these files entirely given we're a library; perhaps it's the same situation as `Gemfile.lock`. Opinions welcome!

**Pull request merged**
