### PR TITLE
Remove trailing space from generated yaml warning message 

### PR DESCRIPTION
**Pull request by piao-mdsol**
Hi there 👋 

Noticed a trailing space 👾 is left in the generated yaml warning message. 👇 

screenshot 2018-08-01 14 31 16

So take the chance to chop it ✂️ 🙂

FYI @mdsol/team-10

### CODE REVIEW

**Comment by piao-mdsol** [comment]
Hmm, not sure about the CI failure, seems not related though 😕 https://travis-ci.org/mdsol/dice_bag/jobs/410648898

image

**Comment by piao-mdsol** [comment]
I see.. we're removing failing ruby 1.9.3 from the CI in https://github.com/mdsol/dice_bag/pull/83/files#diff-354f30a63fb0907d4ad57269548329e3L3

**Comment by jfeltesse-mdsol** [comment]
since the code has changed, even a TEENY update may be needed.

- [ ] version bump
- [ ] changelog

**Comment by piao-mdsol** [comment]
Bumped and updated 8917c4b 🆙 🎈 (Waiting for #83 to fix the CI, will rebase after that)

**Comment by piao-mdsol** [comment]
@mdsol/team-10 Rebased and now CI passed, please 🙏

**Comment by jfeltesse-mdsol** [comment]
wasn't this the PR where you'd update the changelog and do a TEENY bump?

**Comment by piao-mdsol** [comment]
@jfeltesse-mdsol sorry I got completely lost between switching branches 😓 🙇 🤦‍♂️

**Review by jfeltesse-mdsol — APPROVED** [review]

**Pull request merged**
