### PR TITLE
Enable rubocop on CI

### PR DESCRIPTION
**Pull request by mjobin-mdsol**

### CODE REVIEW

**Review by jcarres-mdsol — APPROVED** [review]
Thanks so much!

**Comment by jfeltesse-mdsol** [comment]
@jcarres-mdsol when are we removing support for ruby < 2.5? Seems that's preventing rubocop to be simply added to the gemspec where it could have a looser version constraint.

**Comment by jcarres-mdsol** [comment]
@jfeltesse-mdsol I checked you know what and dropping < 2.5 sounds safe to me.

**Comment by mjobin-mdsol** [comment]
I also think we could remove support for 2.3 and 2.4, but I did not want to do this within this PR
it's not the reason I have not added the gem to the gemspec though, I find that equivalent installing it in travis, since its not required to be in the gemspec.

the lock on 1.3.1 is not due to ruby 2.3, but there is a bug with 1.4 and dice_bag is impacted.
I'll keep an eye on the next release and see if I can make it better in a subsequent PR

**Comment by jfeltesse-mdsol** [comment]
Having the gem in the development deps in the gemspec has the following pros:
- it'll be fetched when you run bundle install/update, not just on the CI, and no separate bundle install + gem install in travis: less commands, faster.
- you can specify a constraint like `~> 1.3.1` in this case.

How about having a separate PR that drops 2.3 and 2.4 first and then rebase on top of it in this branch?

**Comment by mjobin-mdsol** [comment]
either way, I can put it into the gemspec after 2.3 is removed and rubocop 1.5 is released and tested.

**Comment by jcarres-mdsol** [comment]
I'm merging this but please @mjobin-mdsol do not forget following up  with Julien's suggestions when 1.5 is out.

**Comment by jfeltesse-mdsol** [comment]
1.6.1 is out https://rubygems.org/gems/rubocop 😅

**Pull request merged**
