### PR TITLE
update change log and version from recent PRs

### PR DESCRIPTION
**Pull request by mjobin-mdsol**
updating Changelog with recent PRs and bumping version to 0.8.0

I think 0.7.1 should have been tagged as of PR #60

### CODE REVIEW

**Comment by jcarres-mdsol** [comment]
Very nice :sushi:  :+1:

**Comment by jcarres-mdsol** [comment]
I've tagged as v0.8.0 and pushed it

**Comment by mjobin-mdsol** [comment]
can you also release it to the wild, so that it appears on https://rubygems.org/gems/dice_bag ? 

is it as simple as doing `rake release`  ?

**Comment by jcarres-mdsol** [comment]
It is as simple as that but you need to have the correct key for the account owning it in rubygems and I do not have it

**Comment by mjobin-mdsol** [comment]
@asmith-mdsol can you release 0.8.0 to the wild ?

**Pull request merged**
