### PR TITLE
Added support for RSA Private keys that lack spaces. MCC-62361

### PR DESCRIPTION
**Pull request by clabrunda**
Cucumber output:

22 scenarios (22 passed)
86 steps (86 passed)
0m16.306s

### CODE REVIEW

**Comment by clabrunda** [comment]
@jcarres-mdsol @asmith-mdsol 
Just tagging you guys so you see this.  It's a short PR.

**Comment by jcarres-mdsol** [comment]
+1 
You should update to 0.7.1 and add a line in the changelog also

**Comment by clabrunda** [comment]
I updated the Changelog, including two lines about the 0.70 release.

**Comment by clabrunda** [comment]
All comments addressed.

**Pull request merged**
