### PR TITLE
Make committed templates the norm

### PR DESCRIPTION
**Pull request by asmith-mdsol**
After a long discussion with @fosdev I came the realization that the automagical creation of configuration templates are runtime was a misfeature, which added unnecessary complexity and confusion and that @jcarres-mdsol was correct all along. This pull request is a first step in backing out the old behaviour.

The primary changes here are to make `.dice` the _only_ file extension for configuration templates and stop the `config:all` rake task call the `config:generate_all` task. The documentation is changed in line and now implyies the need to commit configuration templates. The old behaviour is maintained for now as I need to give time to people currently using DiceBag like @HonoreDB and @dhoizner-mdsol to adapt.

### CODE REVIEW

**Comment by harryw** [comment]
I like this.

**Comment by fosdev** [comment]
@asmith-mdsol Will this pick up templates in libraries already? Do they all default to config/ folder or how can that be specified?

**Comment by asmith-mdsol** [comment]
@fosdev Not sure I understand your question. We're entirely separating config template generation from config template processing (leading to an instantiated config file). Libraries can provide templates for generation as before, with any of the supported file extensions, although `.dice` being correct from this point forward. If your question was "can libraries already provide templates?" then the answers is "yes", as described in the "templates.md" file in the root. I believe they currently default to the "config" directory although it's been a while since I've walked through that code and its getting late here and my brain's going to sleep. It's entirely possible this is borked right now and we badly need some test coverage. :worried:

**Comment by fosdev** [comment]
Thanks. That does answer the question.

**Comment by jcarres-mdsol** [comment]
Good.

**Pull request merged**
